{
 "title": "Сравнение результатов НТ",
 "time": { "from": "2020-08-04T11:13:32.695Z", "to": "2020-08-04T11:25:28.899Z" },
 "templating": {
  "list": [
   {
    "name": "LEFT_PROFILE",
    "query": "SELECT DISTINCT profile_name FROM jmresults_statistic"
   },
   {
    "name": "LEFT_RUN",
    "query": "SELECT DISTINCT run_id FROM jmresults_statistic where profile_name ='$LEFT_PROFILE'"
   },
   {
    "name": "RIGHT_PROFILE",
    "query": "SELECT DISTINCT profile_name FROM jmresults_statistic"
   },
   {
    "name": "RIGHT_RUN",
    "query": "SELECT DISTINCT run_id FROM jmresults_statistic where profile_name ='$RIGHT_PROFILE'"
   },
   {
    "name": "LEFT_SAMPLE",
    "label": "Sample",
    "query": "SELECT DISTINCT sample_label FROM jmresults_statistic where profile_name ='$LEFT_PROFILE' and run_id='$LEFT_RUN'"
   },
   { "name": "agr", "query": "1,10,60,1800,3600" },
   {
    "name": "percentline",
    "query": "99,95,90,85,80,70,60,50,40,30,20,10"
   }
  ]
 },
 "panels": [
  {
   "title": "Percentile Distribution Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Percentil Graf Left Run $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "repeat": "LEFT_SAMPLE",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n   \n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$LEFT_PROFILE'\n    and run_id = '$LEFT_RUN' and res_code='200' and sample_label in ($LEFT_SAMPLE) \nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT         quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run8' and res_code='200' and sample_label in ('jp@gc - Dummy Sampler3')  GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Graf $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "repeat": "LEFT_SAMPLE",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$RIGHT_PROFILE'\n    and run_id = '$RIGHT_RUN' and res_code='200' and sample_label  in ($LEFT_SAMPLE)\nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run9' and res_code='200' and sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Diff $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "repeat": "LEFT_SAMPLE",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$LEFT_PROFILE'\r\n    and js.run_id = '$LEFT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label\r\n    union all\r\nSELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$RIGHT_PROFILE'\r\n    and js.run_id = '$RIGHT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run8' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label     union all SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run9' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentil Graf Left Run $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n   \n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$LEFT_PROFILE'\n    and run_id = '$LEFT_RUN' and res_code='200' and sample_label in ($LEFT_SAMPLE) \nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT         quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run8' and res_code='200' and sample_label in ('jp@gc - Dummy Sampler3')  GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Graf $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$RIGHT_PROFILE'\n    and run_id = '$RIGHT_RUN' and res_code='200' and sample_label  in ($LEFT_SAMPLE)\nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run9' and res_code='200' and sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Diff $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$LEFT_PROFILE'\r\n    and js.run_id = '$LEFT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label\r\n    union all\r\nSELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$RIGHT_PROFILE'\r\n    and js.run_id = '$RIGHT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run8' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label     union all SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run9' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentil Graf Left Run $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n   \n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$LEFT_PROFILE'\n    and run_id = '$LEFT_RUN' and res_code='200' and sample_label in ($LEFT_SAMPLE) \nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT         quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run8' and res_code='200' and sample_label in ('jp@gc - Dummy Sampler3')  GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Graf $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quantile(0.99)(average_time) as \"99\",\n    quantile(0.95)(average_time) as \"95\",\n    quantile(0.90)(average_time) as \"90\",\n     quantile(0.80)(average_time) as \"80\",\n     quantile(0.70)(average_time) as \"70\",\n      quantile(0.60)(average_time) as \"60\",\n       quantile(0.50)(average_time) as \"50\",\n        quantile(0.40)(average_time) as \"40\",\n         quantile(0.30)(average_time) as \"30\",\n          quantile(0.20)(average_time) as \"20\",\n           quantile(0.10)(average_time) as \"10\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$RIGHT_PROFILE'\n    and run_id = '$RIGHT_RUN' and res_code='200' and sample_label  in ($LEFT_SAMPLE)\nGROUP BY\n    \n    sample_label\nORDER BY\n    \n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(average_time) as \"99\",     quantile(0.95)(average_time) as \"95\",     quantile(0.90)(average_time) as \"90\",      quantile(0.80)(average_time) as \"80\",      quantile(0.70)(average_time) as \"70\",       quantile(0.60)(average_time) as \"60\",        quantile(0.50)(average_time) as \"50\",         quantile(0.40)(average_time) as \"40\",          quantile(0.30)(average_time) as \"30\",           quantile(0.20)(average_time) as \"20\",            quantile(0.10)(average_time) as \"10\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run9' and res_code='200' and sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY          sample_label ORDER BY          sample_label",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Percentile Diff $LEFT_SAMPLE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$LEFT_PROFILE'\r\n    and js.run_id = '$LEFT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label\r\n    union all\r\nSELECT\r\n    quantile(0.99)(js.average_time) as \"99\",\r\n    quantile(0.95)(js.average_time) as \"95\",\r\n    quantile(0.90)(js.average_time) as \"90\",\r\n     quantile(0.80)(js.average_time) as \"80\",\r\n     quantile(0.70)(js.average_time) as \"70\",\r\n      quantile(0.60)(js.average_time) as \"60\",\r\n       quantile(0.50)(js.average_time) as \"50\",\r\n        quantile(0.40)(js.average_time) as \"40\",\r\n         quantile(0.30)(js.average_time) as \"30\",\r\n          quantile(0.20)(js.average_time) as \"20\",\r\n           quantile(0.10)(js.average_time) as \"10\"\r\nFROM jmresults_statistic js\r\nWHERE\r\n    js.profile_name = '$RIGHT_PROFILE'\r\n    and js.run_id = '$RIGHT_RUN' and js.sample_label  in ($LEFT_SAMPLE)\r\nGROUP BY\r\n    sample_label\r\nORDER BY\r\n    sample_label",
     "rawQuery": "SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run8' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label     union all SELECT     quantile(0.99)(js.average_time) as \"99\",     quantile(0.95)(js.average_time) as \"95\",     quantile(0.90)(js.average_time) as \"90\",      quantile(0.80)(js.average_time) as \"80\",      quantile(0.70)(js.average_time) as \"70\",       quantile(0.60)(js.average_time) as \"60\",        quantile(0.50)(js.average_time) as \"50\",         quantile(0.40)(js.average_time) as \"40\",          quantile(0.30)(js.average_time) as \"30\",           quantile(0.20)(js.average_time) as \"20\",            quantile(0.10)(js.average_time) as \"10\" FROM jmresults_statistic js WHERE     js.profile_name = 'TEST3'     and js.run_id = 'Run9' and js.sample_label  in ('jp@gc - Dummy Sampler3') GROUP BY     sample_label ORDER BY     sample_label",
     "round": "0s"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Response time Graf",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "90 perc",
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT percentile(\"responseTime\", 90) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "WITH\n    (select min(timestamp_sec) from jmresults_statistic where profile_name = '$LEFT_PROFILE' and run_id = '$LEFT_RUN') as left_test,\n    (select min(timestamp_sec) from jmresults_statistic where profile_name = '$RIGHT_PROFILE' and run_id = '$RIGHT_RUN') as right_test\n    SELECT (intDiv(toUInt32(timestamp_sec-(right_test - left_test)), $agr) * $agr) * 1000  as t,\n    quantile(0.95)(average_time) as \"97perc\",\n    sample_label|| '_RIGHT'  as \"sample_label\"\nFROM jmresults_statistic js\nWHERE\n    profile_name = '$RIGHT_PROFILE'\n    and run_id = '$RIGHT_RUN' and res_code='200'\nGROUP BY\n    t,\n    sample_label\nORDER BY \n    t,sample_label\n    ",
     "rawQuery": "WITH     (select min(timestamp_sec) from jmresults_statistic where profile_name = 'TEST3' and run_id = 'Run8') as left_test,     (select min(timestamp_sec) from jmresults_statistic where profile_name = 'TEST3' and run_id = 'Run9') as right_test     SELECT (intDiv(toUInt32(timestamp_sec-(right_test - left_test)), 10) * 10) * 1000  as t,     quantile(0.95)(average_time) as \"97perc\",     sample_label|| '_RIGHT'  as \"sample_label\" FROM jmresults_statistic js WHERE     profile_name = 'TEST3'     and run_id = 'Run9' and res_code='200' GROUP BY     t,     sample_label ORDER BY      t,sample_label",
     "round": "0s",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "table": "jmresults",
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "90 perc",
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT percentile(\"responseTime\", 90) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT\n    $timeSeries as t,\n    quantile(0.95)(average_time) as \"97perc\",\n    sample_label||'_LEFT' as \"sample_label\"\nFROM jmresults_statistic\nWHERE\n    $timeFilter\n    AND profile_name = '$LEFT_PROFILE'\n    and run_id = '$LEFT_RUN' and res_code='200'\n    \nGROUP BY t,sample_label\nORDER BY t,sample_label",
     "rawQuery": "SELECT     (intDiv(toUInt32(timestamp_sec), 10) * 10) * 1000 as t,     quantile(0.95)(average_time) as \"97perc\",     sample_label||'_LEFT' as \"sample_label\" FROM jmresults_statistic WHERE     timestamp_sec BETWEEN toDateTime(1596539790) AND toDateTime(1596540150)     AND profile_name = 'TEST3'     and run_id = 'Run8' and res_code='200'      GROUP BY t,sample_label ORDER BY t,sample_label",
     "round": "0s",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "table": "jmresults",
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Left",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT     sample_label,sum(points_count) as \"Samples\",\r\nquantile(0.95)(average_time) as \"95%\"\r\nFROM jmresults_statistic \r\nWHERE\r\nprofile_name = '$LEFT_PROFILE'     \r\nand run_id = '$LEFT_RUN'    \r\nGROUP BY sample_label ORDER BY sample_label",
     "rawQuery": "SELECT     sample_label,sum(points_count) as \"Samples\", quantile(0.95)(average_time) as \"95%\" FROM jmresults_statistic  WHERE profile_name = 'TEST3'      and run_id = 'Run3'     GROUP BY sample_label ORDER BY sample_label",
     "round": "0s",
     "table": "jmresults_statistic"
    }
   ]
  },
  {
   "title": "Right",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT     sample_label,sum(points_count) as \"Samples\",\r\nquantile(0.95)(average_time) as \"95%\"\r\nFROM jmresults_statistic \r\nWHERE\r\nprofile_name = '$RIGHT_PROFILE'     \r\nand run_id = '$RIGHT_RUN'    \r\nGROUP BY sample_label ORDER BY sample_label",
     "rawQuery": "SELECT     sample_label,sum(points_count) as \"Samples\", quantile(0.95)(average_time) as \"95%\" FROM jmresults_statistic  WHERE profile_name = 'TEST3'      and run_id = 'Run4'     GROUP BY sample_label ORDER BY sample_label",
     "round": "0s",
     "table": "jmresults_statistic"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "timestamp_sec",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select a.sample_label as \"Label\", a.\"97per\" as \"Left\",b.\"97per\" as \"Right\" from (\r\nSELECT     sample_label,\r\nquantile(0.95)(average_time) as \"97per\"\r\nFROM jmresults_statistic \r\nWHERE\r\nprofile_name = '$LEFT_PROFILE'     \r\nand run_id = '$LEFT_RUN'    \r\nGROUP BY sample_label ORDER BY sample_label) a, (\r\nSELECT     sample_label,\r\nquantile(0.95)(average_time) as \"97per\"\r\nFROM jmresults_statistic \r\nWHERE\r\nprofile_name = '$RIGHT_PROFILE'     \r\nand run_id = '$RIGHT_RUN'    \r\nGROUP BY sample_label ORDER BY sample_label) b where a.sample_label=b.sample_label order by \"Label\"",
     "rawQuery": "select a.sample_label as \"Label\", a.\"97per\" as \"Left\",b.\"97per\" as \"Right\" from ( SELECT     sample_label, quantile(0.95)(average_time) as \"97per\" FROM jmresults_statistic  WHERE profile_name = 'TEST3'      and run_id = 'Run3'     GROUP BY sample_label ORDER BY sample_label) a, ( SELECT     sample_label, quantile(0.95)(average_time) as \"97per\" FROM jmresults_statistic  WHERE profile_name = 'TEST3'      and run_id = 'Run4'     GROUP BY sample_label ORDER BY sample_label) b where a.sample_label=b.sample_label order by \"Label\"",
     "round": "0s",
     "table": "jmresults_statistic"
    }
   ]
  }
 ]
}